/**
 * Hand-maintained seed for the offline common-plants index (see
 * docs/superpowers/specs/2026-06-13-common-name-species-autocomplete-design.md).
 *
 * Each entry pairs the everyday common name novices type with the canonical
 * cultivated species. The scientific name is what the generator resolves against
 * the GBIF backbone (the /species/match endpoint is authoritative for scientific
 * names but returns NONE — or an unrelated species — for ambiguous common names
 * like "tomato" or "cilantro", so the curator pins the right species here). The
 * common name is guaranteed into the generated index because GBIF's English
 * vernaculars often omit the everyday word (e.g. it lists "Garden Tomato", not
 * "tomato"). This is the only hand-edited artifact and is meant to grow.
 */
export interface CommonPlantSeed {
  /** Everyday name a novice types; always kept searchable in the index. */
  common: string;
  /** Canonical cultivated species, resolved authoritatively via GBIF match. */
  scientific: string;
}

export const COMMON_PLANT_SEED: readonly CommonPlantSeed[] = [
  // Herbs
  { common: 'basil', scientific: 'Ocimum basilicum' },
  { common: 'holy basil', scientific: 'Ocimum tenuiflorum' },
  { common: 'mint', scientific: 'Mentha spicata' },
  { common: 'peppermint', scientific: 'Mentha x piperita' },
  { common: 'rosemary', scientific: 'Salvia rosmarinus' },
  { common: 'thyme', scientific: 'Thymus vulgaris' },
  { common: 'oregano', scientific: 'Origanum vulgare' },
  { common: 'marjoram', scientific: 'Origanum majorana' },
  { common: 'parsley', scientific: 'Petroselinum crispum' },
  { common: 'cilantro', scientific: 'Coriandrum sativum' },
  { common: 'sage', scientific: 'Salvia officinalis' },
  { common: 'dill', scientific: 'Anethum graveolens' },
  { common: 'chives', scientific: 'Allium schoenoprasum' },
  { common: 'tarragon', scientific: 'Artemisia dracunculus' },
  { common: 'lemon balm', scientific: 'Melissa officinalis' },
  { common: 'lemongrass', scientific: 'Cymbopogon citratus' },
  { common: 'fennel', scientific: 'Foeniculum vulgare' },
  { common: 'lavender', scientific: 'Lavandula angustifolia' },
  // Vegetables & fruit
  { common: 'tomato', scientific: 'Solanum lycopersicum' },
  { common: 'chili pepper', scientific: 'Capsicum frutescens' },
  { common: 'bell pepper', scientific: 'Capsicum annuum' },
  { common: 'cucumber', scientific: 'Cucumis sativus' },
  { common: 'lettuce', scientific: 'Lactuca sativa' },
  { common: 'spinach', scientific: 'Spinacia oleracea' },
  { common: 'kale', scientific: 'Brassica oleracea' },
  { common: 'arugula', scientific: 'Eruca vesicaria' },
  { common: 'strawberry', scientific: 'Fragaria x ananassa' },
  { common: 'zucchini', scientific: 'Cucurbita pepo' },
  { common: 'eggplant', scientific: 'Solanum melongena' },
  { common: 'radish', scientific: 'Raphanus sativus' },
  { common: 'carrot', scientific: 'Daucus carota' },
  // Foliage houseplants
  { common: 'snake plant', scientific: 'Dracaena trifasciata' },
  { common: 'golden pothos', scientific: 'Epipremnum aureum' },
  { common: 'monstera', scientific: 'Monstera deliciosa' },
  { common: 'swiss cheese plant', scientific: 'Monstera adansonii' },
  { common: 'peace lily', scientific: 'Spathiphyllum wallisii' },
  { common: 'spider plant', scientific: 'Chlorophytum comosum' },
  { common: 'ZZ plant', scientific: 'Zamioculcas zamiifolia' },
  { common: 'fiddle leaf fig', scientific: 'Ficus lyrata' },
  { common: 'rubber plant', scientific: 'Ficus elastica' },
  { common: 'jade plant', scientific: 'Crassula ovata' },
  { common: 'boston fern', scientific: 'Nephrolepis exaltata' },
  { common: 'english ivy', scientific: 'Hedera helix' },
  { common: 'heartleaf philodendron', scientific: 'Philodendron hederaceum' },
  { common: 'chinese evergreen', scientific: 'Aglaonema commutatum' },
  { common: 'dumb cane', scientific: 'Dieffenbachia seguine' },
  { common: 'croton', scientific: 'Codiaeum variegatum' },
  { common: 'dragon tree', scientific: 'Dracaena marginata' },
  { common: 'weeping fig', scientific: 'Ficus benjamina' },
  { common: 'umbrella tree', scientific: 'Schefflera actinophylla' },
  { common: 'arrowhead plant', scientific: 'Syngonium podophyllum' },
  { common: 'wandering jew', scientific: 'Tradescantia zebrina' },
  // Palms & tropicals
  { common: 'areca palm', scientific: 'Dypsis lutescens' },
  { common: 'parlour palm', scientific: 'Chamaedorea elegans' },
  { common: 'kentia palm', scientific: 'Howea forsteriana' },
  { common: 'bird of paradise', scientific: 'Strelitzia reginae' },
  { common: 'banana plant', scientific: 'Musa acuminata' },
  // Prayer / foliage colour
  { common: 'calathea', scientific: 'Calathea makoyana' },
  { common: 'prayer plant', scientific: 'Maranta leuconeura' },
  { common: 'nerve plant', scientific: 'Fittonia albivenis' },
  // Succulents & cacti
  { common: 'aloe vera', scientific: 'Aloe vera' },
  { common: 'echeveria', scientific: 'Echeveria elegans' },
  { common: 'haworthia', scientific: 'Haworthia cooperi' },
  { common: 'christmas cactus', scientific: 'Schlumbergera truncata' },
  { common: 'string of pearls', scientific: 'Curio rowleyanus' },
  // Flowering
  { common: 'orchid', scientific: 'Phalaenopsis amabilis' },
  { common: 'moth orchid', scientific: 'Phalaenopsis aphrodite' },
  { common: 'african violet', scientific: 'Streptocarpus ionanthus' },
  { common: 'begonia', scientific: 'Begonia rex' },
  { common: 'geranium', scientific: 'Pelargonium zonale' },
  { common: 'cyclamen', scientific: 'Cyclamen persicum' },
  { common: 'anthurium', scientific: 'Anthurium andraeanum' },
  { common: 'kalanchoe', scientific: 'Kalanchoe blossfeldiana' },
  { common: 'hibiscus', scientific: 'Hibiscus rosa-sinensis' },
  { common: 'jasmine', scientific: 'Jasminum officinale' },
  { common: 'poinsettia', scientific: 'Euphorbia pulcherrima' },
  // Aroids (foliage)
  { common: 'tree philodendron', scientific: 'Philodendron bipinnatifidum' },
  { common: 'blushing philodendron', scientific: 'Philodendron erubescens' },
  { common: 'velvet leaf philodendron', scientific: 'Philodendron gloriosum' },
  { common: 'black gold philodendron', scientific: 'Philodendron melanochrysum' },
  { common: 'silver sword philodendron', scientific: 'Philodendron hastatum' },
  { common: 'philodendron squamiferum', scientific: 'Philodendron squamiferum' },
  { common: 'mini monstera', scientific: 'Rhaphidophora tetrasperma' },
  { common: 'satin pothos', scientific: 'Scindapsus pictus' },
  { common: 'dragon tail plant', scientific: 'Epipremnum pinnatum' },
  { common: 'kris plant', scientific: 'Alocasia sanderiana' },
  { common: 'giant taro', scientific: 'Alocasia macrorrhizos' },
  { common: 'zebra alocasia', scientific: 'Alocasia zebrina' },
  { common: 'jewel alocasia', scientific: 'Alocasia cuprea' },
  { common: 'black velvet alocasia', scientific: 'Alocasia reginula' },
  { common: 'elephant ear', scientific: 'Colocasia esculenta' },
  { common: 'caladium', scientific: 'Caladium bicolor' },
  { common: 'crystal anthurium', scientific: 'Anthurium crystallinum' },
  { common: 'velvet cardboard anthurium', scientific: 'Anthurium clarinervium' },
  { common: 'flamingo flower', scientific: 'Anthurium scherzerianum' },
  { common: 'calla lily', scientific: 'Zantedeschia aethiopica' },
  { common: 'chinese evergreen modestum', scientific: 'Aglaonema modestum' },
  // Ferns
  { common: "bird's nest fern", scientific: 'Asplenium nidus' },
  { common: 'staghorn fern', scientific: 'Platycerium bifurcatum' },
  { common: 'maidenhair fern', scientific: 'Adiantum raddianum' },
  { common: 'button fern', scientific: 'Pellaea rotundifolia' },
  { common: "rabbit's foot fern", scientific: 'Davallia fejeensis' },
  { common: 'blue star fern', scientific: 'Phlebodium aureum' },
  { common: 'kimberly queen fern', scientific: 'Nephrolepis obliterata' },
  { common: 'asparagus fern', scientific: 'Asparagus setaceus' },
  { common: 'foxtail fern', scientific: 'Asparagus densiflorus' },
  { common: 'crocodile fern', scientific: 'Microsorum musifolium' },
  { common: 'autumn fern', scientific: 'Dryopteris erythrosora' },
  { common: 'holly fern', scientific: 'Cyrtomium falcatum' },
  // Palms & cycads
  { common: 'majesty palm', scientific: 'Ravenea rivularis' },
  { common: 'ponytail palm', scientific: 'Beaucarnea recurvata' },
  { common: 'sago palm', scientific: 'Cycas revoluta' },
  { common: 'lady palm', scientific: 'Rhapis excelsa' },
  { common: 'fishtail palm', scientific: 'Caryota mitis' },
  { common: 'pygmy date palm', scientific: 'Phoenix roebelenii' },
  { common: 'chinese fan palm', scientific: 'Livistona chinensis' },
  { common: 'bamboo palm', scientific: 'Chamaedorea seifrizii' },
  { common: 'cat palm', scientific: 'Chamaedorea cataractarum' },
  { common: 'coconut palm', scientific: 'Cocos nucifera' },
  // Succulents
  { common: "burro's tail", scientific: 'Sedum morganianum' },
  { common: 'string of bananas', scientific: 'Curio radicans' },
  { common: 'string of hearts', scientific: 'Ceropegia woodii' },
  { common: 'panda plant', scientific: 'Kalanchoe tomentosa' },
  { common: 'paddle plant', scientific: 'Kalanchoe luciae' },
  { common: 'mother of thousands', scientific: 'Kalanchoe daigremontiana' },
  { common: 'zebra haworthia', scientific: 'Haworthiopsis attenuata' },
  { common: 'ox tongue', scientific: 'Gasteria bicolor' },
  { common: 'crown of thorns', scientific: 'Euphorbia milii' },
  { common: 'pencil cactus', scientific: 'Euphorbia tirucalli' },
  { common: 'african milk tree', scientific: 'Euphorbia trigona' },
  { common: 'tree aeonium', scientific: 'Aeonium arboreum' },
  { common: 'ghost plant', scientific: 'Graptopetalum paraguayense' },
  { common: 'hens and chicks', scientific: 'Sempervivum tectorum' },
  { common: 'century plant', scientific: 'Agave americana' },
  { common: 'cylindrical snake plant', scientific: 'Dracaena angolensis' },
  { common: 'living stones', scientific: 'Lithops lesliei' },
  { common: 'string of buttons', scientific: 'Crassula perforata' },
  { common: 'silver dollar plant', scientific: 'Crassula arborescens' },
  { common: 'watch chain', scientific: 'Crassula muscosa' },
  { common: 'elephant bush', scientific: 'Portulacaria afra' },
  // Cacti
  { common: 'bunny ears cactus', scientific: 'Opuntia microdasys' },
  { common: 'golden barrel cactus', scientific: 'Echinocactus grusonii' },
  { common: 'old lady cactus', scientific: 'Mammillaria hahniana' },
  { common: 'moon cactus', scientific: 'Gymnocalycium mihanovichii' },
  { common: 'fishbone cactus', scientific: 'Epiphyllum anguliger' },
  { common: 'mistletoe cactus', scientific: 'Rhipsalis baccifera' },
  { common: 'prickly pear', scientific: 'Opuntia ficus-indica' },
  // Hoyas, peperomias & trailing
  { common: 'wax plant', scientific: 'Hoya carnosa' },
  { common: 'sweetheart hoya', scientific: 'Hoya kerrii' },
  { common: 'string of turtles', scientific: 'Peperomia prostrata' },
  { common: 'watermelon peperomia', scientific: 'Peperomia argyreia' },
  { common: 'baby rubber plant', scientific: 'Peperomia obtusifolia' },
  { common: 'emerald ripple peperomia', scientific: 'Peperomia caperata' },
  { common: 'raindrop peperomia', scientific: 'Peperomia polybotrya' },
  { common: 'trailing jade peperomia', scientific: 'Peperomia rotundifolia' },
  { common: 'small-leaf spiderwort', scientific: 'Tradescantia fluminensis' },
  { common: 'purple heart', scientific: 'Tradescantia pallida' },
  { common: 'moses in the cradle', scientific: 'Tradescantia spathacea' },
  { common: 'creeping fig', scientific: 'Ficus pumila' },
  // Begonias & foliage colour
  { common: 'polka dot begonia', scientific: 'Begonia maculata' },
  { common: 'angel wing begonia', scientific: 'Begonia coccinea' },
  { common: 'iron cross begonia', scientific: 'Begonia masoniana' },
  { common: 'coleus', scientific: 'Coleus scutellarioides' },
  { common: 'polka dot plant', scientific: 'Hypoestes phyllostachya' },
  { common: 'aluminum plant', scientific: 'Pilea cadierei' },
  { common: 'chinese money plant', scientific: 'Pilea peperomioides' },
  { common: 'friendship plant', scientific: 'Pilea involucrata' },
  { common: 'artillery plant', scientific: 'Pilea microphylla' },
  { common: 'purple passion plant', scientific: 'Gynura aurantiaca' },
  { common: 'persian shield', scientific: 'Strobilanthes dyeriana' },
  { common: 'never never plant', scientific: 'Ctenanthe oppenheimiana' },
  { common: 'rattlesnake plant', scientific: 'Calathea lancifolia' },
  { common: 'pinstripe calathea', scientific: 'Calathea ornata' },
  { common: 'rose painted calathea', scientific: 'Calathea roseopicta' },
  { common: 'network calathea', scientific: 'Calathea musaica' },
  { common: 'zebra calathea', scientific: 'Calathea zebrina' },
  { common: 'ctenanthe', scientific: 'Ctenanthe burle-marxii' },
  { common: 'stromanthe', scientific: 'Stromanthe sanguinea' },
  // Ficus, dracaenas & indoor trees
  { common: 'ficus audrey', scientific: 'Ficus benghalensis' },
  { common: 'money tree', scientific: 'Pachira aquatica' },
  { common: 'norfolk island pine', scientific: 'Araucaria heterophylla' },
  { common: 'corn plant', scientific: 'Dracaena fragrans' },
  { common: 'lucky bamboo', scientific: 'Dracaena sanderiana' },
  { common: 'ti plant', scientific: 'Cordyline fruticosa' },
  { common: 'spineless yucca', scientific: 'Yucca gigantea' },
  { common: 'false aralia', scientific: 'Schefflera elegantissima' },
  { common: 'dwarf umbrella tree', scientific: 'Schefflera arboricola' },
  { common: 'coffee plant', scientific: 'Coffea arabica' },
  { common: 'lemon tree', scientific: 'Citrus limon' },
  { common: 'olive tree', scientific: 'Olea europaea' },
  { common: 'bay laurel', scientific: 'Laurus nobilis' },
  { common: 'common fig', scientific: 'Ficus carica' },
  { common: 'avocado', scientific: 'Persea americana' },
  { common: 'star jasmine', scientific: 'Trachelospermum jasminoides' },
  { common: 'bougainvillea', scientific: 'Bougainvillea glabra' },
  { common: 'mandevilla', scientific: 'Mandevilla sanderi' },
  { common: 'gardenia', scientific: 'Gardenia jasminoides' },
  { common: 'camellia', scientific: 'Camellia japonica' },
  { common: 'florist azalea', scientific: 'Rhododendron simsii' },
  { common: 'hydrangea', scientific: 'Hydrangea macrophylla' },
  // Bromeliads & air plants
  { common: 'scarlet star', scientific: 'Guzmania lingulata' },
  { common: 'pineapple', scientific: 'Ananas comosus' },
  { common: 'urn plant', scientific: 'Aechmea fasciata' },
  { common: 'blushing bromeliad', scientific: 'Neoregelia carolinae' },
  { common: 'air plant', scientific: 'Tillandsia ionantha' },
  { common: "queen's tears", scientific: 'Billbergia nutans' },
  { common: 'flaming sword', scientific: 'Vriesea splendens' },
  // Orchids
  { common: 'dendrobium orchid', scientific: 'Dendrobium nobile' },
  { common: 'cattleya orchid', scientific: 'Cattleya labiata' },
  { common: 'dancing lady orchid', scientific: 'Oncidium sphacelatum' },
  { common: 'cymbidium orchid', scientific: 'Cymbidium ensifolium' },
  { common: 'lady slipper orchid', scientific: 'Paphiopedilum insigne' },
  { common: 'vanda orchid', scientific: 'Vanda coerulea' },
  { common: 'vanilla orchid', scientific: 'Vanilla planifolia' },
  { common: 'jewel orchid', scientific: 'Ludisia discolor' },
  // Carnivorous
  { common: 'venus flytrap', scientific: 'Dionaea muscipula' },
  { common: 'tropical pitcher plant', scientific: 'Nepenthes alata' },
  { common: 'cape sundew', scientific: 'Drosera capensis' },
  { common: 'butterwort', scientific: 'Pinguicula moranensis' },
  { common: 'purple pitcher plant', scientific: 'Sarracenia purpurea' },
  // Flowering & seasonal
  { common: 'amaryllis', scientific: 'Hippeastrum vittatum' },
  { common: 'florist chrysanthemum', scientific: 'Chrysanthemum morifolium' },
  { common: 'gerbera daisy', scientific: 'Gerbera jamesonii' },
  { common: 'marigold', scientific: 'Tagetes erecta' },
  { common: 'impatiens', scientific: 'Impatiens walleriana' },
  { common: 'snapdragon', scientific: 'Antirrhinum majus' },
  { common: 'sunflower', scientific: 'Helianthus annuus' },
  { common: 'nasturtium', scientific: 'Tropaeolum majus' },
  { common: 'hardy fuchsia', scientific: 'Fuchsia magellanica' },
  { common: 'gloxinia', scientific: 'Sinningia speciosa' },
  // Herbs & edibles
  { common: 'catnip', scientific: 'Nepeta cataria' },
  { common: 'stevia', scientific: 'Stevia rebaudiana' },
  { common: 'garlic', scientific: 'Allium sativum' },
  { common: 'onion', scientific: 'Allium cepa' },
  { common: 'leek', scientific: 'Allium ampeloprasum' },
  { common: 'ginger', scientific: 'Zingiber officinale' },
  { common: 'turmeric', scientific: 'Curcuma longa' },
  { common: 'chamomile', scientific: 'Matricaria chamomilla' },
  { common: 'echinacea', scientific: 'Echinacea purpurea' },
  { common: 'common bean', scientific: 'Phaseolus vulgaris' },
  { common: 'pea', scientific: 'Pisum sativum' },
  { common: 'potato', scientific: 'Solanum tuberosum' },
  { common: 'sweet potato', scientific: 'Ipomoea batatas' },
  { common: 'beet', scientific: 'Beta vulgaris' },
  { common: 'celery', scientific: 'Apium graveolens' },
  { common: 'winter squash', scientific: 'Cucurbita maxima' },
  { common: 'watermelon', scientific: 'Citrullus lanatus' },
  { common: 'melon', scientific: 'Cucumis melo' },
  { common: 'okra', scientific: 'Abelmoschus esculentus' },
  { common: 'corn', scientific: 'Zea mays' },
  { common: 'artichoke', scientific: 'Cynara cardunculus' },
  { common: 'blueberry', scientific: 'Vaccinium corymbosum' },
  { common: 'raspberry', scientific: 'Rubus idaeus' },
  { common: 'grape', scientific: 'Vitis vinifera' },
  { common: 'passionfruit', scientific: 'Passiflora edulis' },
];
