/**
 * GENERATED FILE — do not edit by hand. Run `npm run knowledge:build-common-plants`.
 * Offline common-plant name index for the species typeahead. Generated 2026-06-13
 * from the GBIF Backbone Taxonomy (CC BY 4.0 — https://www.gbif.org). Name data
 * only (common <-> scientific); never care data.
 */
export interface CommonPlant {
  scientificName: string;
  commonNames: string[];
}

export const COMMON_PLANTS: readonly CommonPlant[] = [
  { scientificName: "Aglaonema commutatum", commonNames: ["chinese evergreen","Philippine Evergreen","silver queen aglaonema"] },
  { scientificName: "Allium schoenoprasum", commonNames: ["chives","Giant Garlic","Wild Chives"] },
  { scientificName: "Aloe vera", commonNames: ["aloe vera","Aloe","Barbados Aloe","Barbados Aloes","Common Aloes"] },
  { scientificName: "Anethum graveolens", commonNames: ["dill","Dill-weed","Garden Dill","Common Dill"] },
  { scientificName: "Anthurium andraeanum", commonNames: ["anthurium","Flamingo-Lily","flamingo-flower","oilcloth-flower"] },
  { scientificName: "Artemisia dracunculus", commonNames: ["tarragon","False Tarragon","French Tarragon","Green Sagewort","Russian Tarragon"] },
  { scientificName: "Begonia rex", commonNames: ["begonia","Painted-leaf Begonia","Rex begonias","king begonia"] },
  { scientificName: "Brassica oleracea", commonNames: ["kale","Cabbage","Chou Mollier","Haria"] },
  { scientificName: "Calathea makoyana", commonNames: ["calathea"] },
  { scientificName: "Capsicum annuum", commonNames: ["bell pepper","Bird Pepper","Capsicum, Chili, Green Capsicum, Hot Pepper, Paprika, Sweet Pepper","Cayenne Pepper"] },
  { scientificName: "Capsicum frutescens", commonNames: ["chili pepper","Bird Pepper","Capsicum","Hot Pepper","Red Chili"] },
  { scientificName: "Chamaedorea elegans", commonNames: ["parlour palm","Neanthe bella palm","Parlor Palm","good-luck palm"] },
  { scientificName: "Chlorophytum comosum", commonNames: ["spider plant","Bracket plant","Green Hen And Chickens","Hen And Chickens","Hen-And-Chickens"] },
  { scientificName: "Codiaeum variegatum", commonNames: ["croton","Garden Croton"] },
  { scientificName: "Coriandrum sativum", commonNames: ["cilantro","Chinese Parsley","Chinese-parsley","Coriander"] },
  { scientificName: "Crassula ovata", commonNames: ["jade plant","Japanese rubberplant","Japanese-laurel","baby jade"] },
  { scientificName: "Cucumis sativus", commonNames: ["cucumber","Garden Cucumber","cowcumber"] },
  { scientificName: "Cucurbita pepo", commonNames: ["zucchini","Acorn squash","American Pumpkin and Summer Squashes","American pumpkin","Bitter Bottle Gourd"] },
  { scientificName: "Curio rowleyanus", commonNames: ["string of pearls","String-Of-Beads Senecio","String-of-Pearls","string-of-beads"] },
  { scientificName: "Cyclamen persicum", commonNames: ["cyclamen","Common Cyclamen","Florist's Cyclamen","Persian Cyclamen"] },
  { scientificName: "Cymbopogon citratus", commonNames: ["lemongrass","Lemon Grass","West Indian lemongrass","lemon-grass"] },
  { scientificName: "Daucus carota", commonNames: ["carrot","Queen Anne's Lace","Wild Carrot","bishop's lace"] },
  { scientificName: "Dieffenbachia seguine", commonNames: ["dumb cane","Dumb-cane","Dumbcane","dumbplant"] },
  { scientificName: "Dracaena marginata", commonNames: ["dragon tree"] },
  { scientificName: "Dracaena trifasciata", commonNames: ["snake plant","Snake plant, Mother-in-law's tongue, Viper's bowstring hemp, Snake Sansevieria, Bowstring hemp, Good luck plant, Mother-in-law's nose"] },
  { scientificName: "Dypsis lutescens", commonNames: ["areca palm","Yellow Butterfly Palm","butterfly palm","cane palm"] },
  { scientificName: "Echeveria elegans", commonNames: ["echeveria","Mexican snowball","Mexican-gem","pearl echeveria","white Mexican-rose"] },
  { scientificName: "Epipremnum aureum", commonNames: ["golden pothos","Devil's Ivy","Golden pothos, Silver Vine, Money Plant, Devil's Ivy, Solomon Islands' Ivy, Hunter's robe, Ivy arum, Taro vine, Devil's vine","Ivy-arum","Marble Queen"] },
  { scientificName: "Eruca vesicaria", commonNames: ["arugula","Gaden Eruca","Garden Rocket","Rocket","Rocket Salad"] },
  { scientificName: "Euphorbia pulcherrima", commonNames: ["poinsettia","Christmas-flower","Christmas-star","Mexican flameleaf"] },
  { scientificName: "Ficus benjamina", commonNames: ["weeping fig","Ficus","Java fig","Javatree","Malayan banyan"] },
  { scientificName: "Ficus elastica", commonNames: ["rubber plant","India Rubber Tree","Indian Rubber Tree","Rubber Fig"] },
  { scientificName: "Ficus lyrata", commonNames: ["fiddle leaf fig","Fiddle-leaf Fig","Fiddleleaf Fig","banjo fig","lyre-leaf figtree"] },
  { scientificName: "Fittonia albivenis", commonNames: ["nerve plant","mosaic-plant","nerveplant","silver fittonia","silver netleaf"] },
  { scientificName: "Foeniculum vulgare", commonNames: ["fennel","Aniseed-weed","Sweet Fennel","Venkel"] },
  { scientificName: "Fragaria ananassa", commonNames: ["strawberry","Garden Strawberry","cultivated strawberry","dessert strawberry"] },
  { scientificName: "Haworthia cooperi", commonNames: ["haworthia","Bristle Haworthia"] },
  { scientificName: "Hedera helix", commonNames: ["english ivy","English Ivy, Common Ivy, European Ivy, Ivy, Needlepoint Ivy, Ripple Ivy","Ivy","Common Ivy"] },
  { scientificName: "Hibiscus rosa-sinensis", commonNames: ["hibiscus","China-rose","Chinese Hibiscus","Hawaiian hibiscus"] },
  { scientificName: "Howea forsteriana", commonNames: ["kentia palm","Forster sentry palm","Sentrypalm","Thatch Palm"] },
  { scientificName: "Jasminum officinale", commonNames: ["jasmine","Poet's jasmine","Summer Jasmine","common jasmine"] },
  { scientificName: "Kalanchoe blossfeldiana", commonNames: ["kalanchoe","Christmas kalanchoe","Flaming Katy","Florist Kalanchoe","Madagascar Widow's-Thrill"] },
  { scientificName: "Lactuca sativa", commonNames: ["lettuce","Garden Lettuce","Romaine Lettuce","cultivated lettuce"] },
  { scientificName: "Lavandula angustifolia", commonNames: ["lavender","English Lavendar","English Lavender","Garden Lavender"] },
  { scientificName: "Maranta leuconeura", commonNames: ["prayer plant","prayerplant","ten-commandments"] },
  { scientificName: "Melissa officinalis", commonNames: ["lemon balm","Balm","Beebalm","Common Balm","Lemonbalm"] },
  { scientificName: "Mentha piperita", commonNames: ["peppermint","Black Peppermint","Curly Mint","Hairy Peppermint"] },
  { scientificName: "Mentha spicata", commonNames: ["mint","Bush Mint","Spear Mint","Spearmint"] },
  { scientificName: "Monstera adansonii", commonNames: ["swiss cheese plant","Adanson's Monstera","Monkey-Mask","Mountain Ears","Swiss cheese-plant"] },
  { scientificName: "Monstera deliciosa", commonNames: ["monstera","Ceriman","Cut-leaf-philodendron","Delicious Monster","Fruit salad plant"] },
  { scientificName: "Musa acuminata", commonNames: ["banana plant","Cavendish banana","Chinese banana","Edible Banana","Wild Banana"] },
  { scientificName: "Nephrolepis exaltata", commonNames: ["boston fern","Boston Swordfern","Boston sword fern","Sword Fern"] },
  { scientificName: "Ocimum basilicum", commonNames: ["basil","Sweet Basil","sweet-basil","thai basil"] },
  { scientificName: "Ocimum tenuiflorum", commonNames: ["holy basil","Krishna Tulsi","brush-leaf-tea","sacred basil"] },
  { scientificName: "Origanum majorana", commonNames: ["marjoram","Pot Majoram","Pot Marjoram","Pot Marjorum","Sweet marjoram"] },
  { scientificName: "Origanum vulgare", commonNames: ["oregano","Wild Marjoram","winter sweet"] },
  { scientificName: "Pelargonium zonale", commonNames: ["geranium","Horse-shoe Pelargonium","Horseshoe Geranium","Horseshoe Pelargonium","Horseshoe Storksbill"] },
  { scientificName: "Petroselinum crispum", commonNames: ["parsley","Garden Parsley","Common Parsley"] },
  { scientificName: "Phalaenopsis amabilis", commonNames: ["orchid"] },
  { scientificName: "Phalaenopsis aphrodite", commonNames: ["moth orchid"] },
  { scientificName: "Philodendron hederaceum", commonNames: ["heartleaf philodendron","Vilevine","heart-leaf philodendron"] },
  { scientificName: "Raphanus sativus", commonNames: ["radish","Cultivated Radish","Garden Radish","Wild Radish"] },
  { scientificName: "Salvia officinalis", commonNames: ["sage","Common Sage","Culinary Sage","Golden Sage","Kitchen Sage"] },
  { scientificName: "Salvia rosmarinus", commonNames: ["rosemary"] },
  { scientificName: "Schefflera actinophylla", commonNames: ["umbrella tree","Australian cabbagetree","Australian umbrella-tree","Octopus tree","Queensland umbrella-tree"] },
  { scientificName: "Schlumbergera truncata", commonNames: ["christmas cactus","False Christmas Cactus","Thanksgiving cactus","claw cactus","crab cactus"] },
  { scientificName: "Solanum lycopersicum", commonNames: ["tomato","Garden Tomato"] },
  { scientificName: "Solanum melongena", commonNames: ["eggplant","Aubergine","Garden Eggplant, Eggplant","brinjal"] },
  { scientificName: "Spathiphyllum wallisii", commonNames: ["peace lily"] },
  { scientificName: "Spinacia oleracea", commonNames: ["spinach","Spinach [plant]","Spinash"] },
  { scientificName: "Strelitzia reginae", commonNames: ["bird of paradise","Bird-Of-Paradise","common bird-of-paradise flower","craneflower"] },
  { scientificName: "Streptocarpus ionanthus", commonNames: ["african violet","African-violet","Usambara-violet"] },
  { scientificName: "Syngonium podophyllum", commonNames: ["arrowhead plant","African evergreen","American Evergreen","Arrow-Head Vine"] },
  { scientificName: "Thymus vulgaris", commonNames: ["thyme","Common Thyme","English Thyme","Garden Thyme"] },
  { scientificName: "Tradescantia zebrina", commonNames: ["wandering jew","Inch-plant","Inchplant","Inchplant, Wandering jew, Cockroach grass, Purple wandering Jew, Silver inch plant, Striped trad, Striped wandering creeper, Striped wandering Jew, Wandering zebrina, Zebra plant","wandering-Jew"] },
  { scientificName: "Zamioculcas zamiifolia", commonNames: ["ZZ plant","Zanzibar gem","zeezee plant"] },
];
