/**
 * GENERATED FILE — do not edit by hand. Run `npm run knowledge:build-common-plants`.
 * Offline common-plant name index for the species typeahead. Generated 2026-06-14
 * from the GBIF Backbone Taxonomy (CC BY 4.0 — https://www.gbif.org). Name data
 * only (common <-> scientific); never care data.
 */
export interface CommonPlant {
  scientificName: string;
  commonNames: string[];
}

export const COMMON_PLANTS: readonly CommonPlant[] = [
  { scientificName: "Abelmoschus esculentus", commonNames: ["okra","gumbo","lady's finger","lady's-finger"] },
  { scientificName: "Adiantum raddianum", commonNames: ["maidenhair fern","Delta Maidenhair","Delta Maidenhair-fern","Delta maidenhair fern","Fine Maidenhair Fern"] },
  { scientificName: "Aechmea fasciata", commonNames: ["urn plant","Urnplant"] },
  { scientificName: "Aeonium arboreum", commonNames: ["tree aeonium","Tree aenium"] },
  { scientificName: "Agave americana", commonNames: ["century plant","American Agave","American Century Plant","American-aloe","Century-plant"] },
  { scientificName: "Aglaonema commutatum", commonNames: ["chinese evergreen","Philippine Evergreen","silver queen aglaonema"] },
  { scientificName: "Aglaonema modestum", commonNames: ["chinese evergreen modestum","Chinese evergreen","Japanese-leaf"] },
  { scientificName: "Allium ampeloprasum", commonNames: ["leek","Broadleaf Wild Leek","Great-headed Garlic","Levant Garlic"] },
  { scientificName: "Allium cepa", commonNames: ["onion","Garden Onion","Shallot","Spring Onion"] },
  { scientificName: "Allium sativum", commonNames: ["garlic","Cultivated Garlic","garden garlic"] },
  { scientificName: "Allium schoenoprasum", commonNames: ["chives","Giant Garlic","Wild Chives"] },
  { scientificName: "Alocasia cuprea", commonNames: ["jewel alocasia","giant caladium"] },
  { scientificName: "Alocasia macrorrhizos", commonNames: ["giant taro","ape","cunjevoi","elephant's-ear plant"] },
  { scientificName: "Alocasia reginula", commonNames: ["black velvet alocasia"] },
  { scientificName: "Alocasia sanderiana", commonNames: ["kris plant","Kris'-plant","Kris-plant","Sander's Alocasia"] },
  { scientificName: "Alocasia zebrina", commonNames: ["zebra alocasia"] },
  { scientificName: "Aloe vera", commonNames: ["aloe vera","Aloe","Barbados Aloe","Barbados Aloes","Common Aloes"] },
  { scientificName: "Ananas comosus", commonNames: ["pineapple"] },
  { scientificName: "Anethum graveolens", commonNames: ["dill","Dill-weed","Garden Dill","Common Dill"] },
  { scientificName: "Anthurium andraeanum", commonNames: ["anthurium","Flamingo-Lily","flamingo-flower","oilcloth-flower"] },
  { scientificName: "Anthurium clarinervium", commonNames: ["velvet cardboard anthurium"] },
  { scientificName: "Anthurium crystallinum", commonNames: ["crystal anthurium","scalloped laceleaf"] },
  { scientificName: "Anthurium scherzerianum", commonNames: ["flamingo flower"] },
  { scientificName: "Antirrhinum majus", commonNames: ["snapdragon","Garden Snapdragon","Common Snapdragon","Greater Snapdragon"] },
  { scientificName: "Apium graveolens", commonNames: ["celery","Wild Celery"] },
  { scientificName: "Araucaria heterophylla", commonNames: ["norfolk island pine","Norfolk Island araucaria","Norfolk Island-pine","Star Pine"] },
  { scientificName: "Artemisia dracunculus", commonNames: ["tarragon","False Tarragon","French Tarragon","Green Sagewort","Russian Tarragon"] },
  { scientificName: "Asparagus densiflorus", commonNames: ["foxtail fern","Asparagus Fern","Foxtail Asparagus","Sprenger's Asparagus","Sprenger's asparagus fern"] },
  { scientificName: "Asparagus setaceus", commonNames: ["asparagus fern","= Asparagus setaceus (Kunth) Jessop","Climbing asparagus","Common Asparagus Fern"] },
  { scientificName: "Asplenium nidus", commonNames: ["bird's nest fern","Hawai'I Birdnest Fern","bird's-nest fern","nest fern"] },
  { scientificName: "Beaucarnea recurvata", commonNames: ["ponytail palm","Elephant's-foot","Stripy Ponytail","bottle-palm"] },
  { scientificName: "Begonia coccinea", commonNames: ["angel wing begonia","Scarlet Begonia","angel-wing begonia"] },
  { scientificName: "Begonia maculata", commonNames: ["polka dot begonia","Cane Begonia"] },
  { scientificName: "Begonia masoniana", commonNames: ["iron cross begonia","iron-cross begonia"] },
  { scientificName: "Begonia rex", commonNames: ["begonia","Painted-leaf Begonia","Rex begonias","king begonia"] },
  { scientificName: "Beta vulgaris", commonNames: ["beet","Beetroot","Chard","Common Beet"] },
  { scientificName: "Billbergia nutans", commonNames: ["queen's tears","Queen's-Tears","friendship-plant"] },
  { scientificName: "Bougainvillea glabra", commonNames: ["bougainvillea","Paper Flower","Paperflower","lesser bougainvillea"] },
  { scientificName: "Brassica oleracea", commonNames: ["kale","Cabbage","Chou Mollier","Haria"] },
  { scientificName: "Caladium bicolor", commonNames: ["caladium","Angel Wings","Artist's pallet","Heart of Jesus","Heart-of-Jesus"] },
  { scientificName: "Calathea lancifolia", commonNames: ["rattlesnake plant"] },
  { scientificName: "Calathea makoyana", commonNames: ["calathea"] },
  { scientificName: "Calathea musaica", commonNames: ["network calathea"] },
  { scientificName: "Calathea ornata", commonNames: ["pinstripe calathea"] },
  { scientificName: "Calathea roseopicta", commonNames: ["rose painted calathea"] },
  { scientificName: "Calathea zebrina", commonNames: ["zebra calathea","zebraplant"] },
  { scientificName: "Camellia japonica", commonNames: ["camellia","Common camellia","Japanese camellia"] },
  { scientificName: "Capsicum annuum", commonNames: ["bell pepper","Bird Pepper","Capsicum, Chili, Green Capsicum, Hot Pepper, Paprika, Sweet Pepper","Cayenne Pepper"] },
  { scientificName: "Capsicum frutescens", commonNames: ["chili pepper","Bird Pepper","Capsicum","Hot Pepper","Red Chili"] },
  { scientificName: "Caryota mitis", commonNames: ["fishtail palm","Burmese Fishtail Palm","Burmese Fishtail-palm","Clustering fishtail palm","clustered fishtail palm"] },
  { scientificName: "Cattleya labiata", commonNames: ["cattleya orchid"] },
  { scientificName: "Ceropegia woodii", commonNames: ["string of hearts","Rosary Vine","hearts entangled"] },
  { scientificName: "Chamaedorea cataractarum", commonNames: ["cat palm","Cascade Palm"] },
  { scientificName: "Chamaedorea elegans", commonNames: ["parlour palm","Neanthe bella palm","Parlor Palm","good-luck palm"] },
  { scientificName: "Chamaedorea seifrizii", commonNames: ["bamboo palm","Seifriz's Chamaedorea","reed palm"] },
  { scientificName: "Chlorophytum comosum", commonNames: ["spider plant","Bracket plant","Green Hen And Chickens","Hen And Chickens","Hen-And-Chickens"] },
  { scientificName: "Chrysanthemum morifolium", commonNames: ["florist chrysanthemum"] },
  { scientificName: "Citrullus lanatus", commonNames: ["watermelon","Afghan-melon","Bastard-melon","Dessert Watermelon","Water Melon"] },
  { scientificName: "Citrus limon", commonNames: ["lemon tree","Canton lemon","Chinese dwarf lemon","Meyer lemon","Otaheite orange"] },
  { scientificName: "Cocos nucifera", commonNames: ["coconut palm","Coconut","Coconut Tree","Cocopalm"] },
  { scientificName: "Codiaeum variegatum", commonNames: ["croton","Garden Croton"] },
  { scientificName: "Coffea arabica", commonNames: ["coffee plant","Arabian coffee","Arabica Coffee","Arabica coffee, Arabian coffee, Coffee tree, Coffee,","Coffee"] },
  { scientificName: "Coleus scutellarioides", commonNames: ["coleus","Painted nettle","common coleus","painted-nettle"] },
  { scientificName: "Colocasia esculenta", commonNames: ["elephant ear","Arum-Lily Potatoes","Coco yam","Donkey's Ear","Katchu"] },
  { scientificName: "Cordyline fruticosa", commonNames: ["ti plant","Broad-leaved Palm Lily","Good Luck Plant","Pacific Island Cabbage Tree","Palm Lily"] },
  { scientificName: "Coriandrum sativum", commonNames: ["cilantro","Chinese Parsley","Chinese-parsley","Coriander"] },
  { scientificName: "Crassula arborescens", commonNames: ["silver dollar plant","Jade Plant","Silver-dollar Stonecrop","Tree Crassula"] },
  { scientificName: "Crassula muscosa", commonNames: ["watch chain","toy-cypress","watch-chain"] },
  { scientificName: "Crassula ovata", commonNames: ["jade plant","Japanese rubberplant","Japanese-laurel","baby jade"] },
  { scientificName: "Crassula perforata", commonNames: ["string of buttons"] },
  { scientificName: "Ctenanthe burle-marxii", commonNames: ["ctenanthe","Fishbone Prayer Plant"] },
  { scientificName: "Ctenanthe oppenheimiana", commonNames: ["never never plant","Never-never-plant"] },
  { scientificName: "Cucumis melo", commonNames: ["melon","Cantaloupe","Hami melon","Melons"] },
  { scientificName: "Cucumis sativus", commonNames: ["cucumber","Garden Cucumber","cowcumber"] },
  { scientificName: "Cucurbita maxima", commonNames: ["winter squash","Atlantic Giant Pumpkin","Banana Squash","Buttercup Squash","Great Pumpkin"] },
  { scientificName: "Cucurbita pepo", commonNames: ["zucchini","Acorn squash","American Pumpkin and Summer Squashes","American pumpkin","Bitter Bottle Gourd"] },
  { scientificName: "Curcuma longa", commonNames: ["turmeric","Common Turmeric","Indian-saffron"] },
  { scientificName: "Curio radicans", commonNames: ["string of bananas","Baboon Toes","Banana Vine","Creeping Berry","Necklace Plant"] },
  { scientificName: "Curio rowleyanus", commonNames: ["string of pearls","String-Of-Beads Senecio","String-of-Pearls","string-of-beads"] },
  { scientificName: "Cycas revoluta", commonNames: ["sago palm","Fern Palm","Sago palm, King sago, Sago cycad, Japanese sago palm","sago cycas"] },
  { scientificName: "Cyclamen persicum", commonNames: ["cyclamen","Common Cyclamen","Florist's Cyclamen","Persian Cyclamen"] },
  { scientificName: "Cymbidium ensifolium", commonNames: ["cymbidium orchid","Four-season orchid","Fukien-orchid"] },
  { scientificName: "Cymbopogon citratus", commonNames: ["lemongrass","Lemon Grass","West Indian lemongrass","lemon-grass"] },
  { scientificName: "Cynara cardunculus", commonNames: ["artichoke","Cardoon","Globe Artichoke","Scotch thistle","Scottish thistle"] },
  { scientificName: "Cyrtomium falcatum", commonNames: ["holly fern","Asian Hollyfern","House Holly-Fern","Japanese Holly Fern"] },
  { scientificName: "Daucus carota", commonNames: ["carrot","Queen Anne's Lace","Wild Carrot","bishop's lace"] },
  { scientificName: "Davallia fejeensis", commonNames: ["rabbit's foot fern","Lacy hare's-foot fern"] },
  { scientificName: "Dendrobium nobile", commonNames: ["dendrobium orchid","Noble Dendrobium"] },
  { scientificName: "Dieffenbachia seguine", commonNames: ["dumb cane","Dumb-cane","Dumbcane","dumbplant"] },
  { scientificName: "Dionaea muscipula", commonNames: ["venus flytrap","Venus fly trap","Venus fly-trap","Venus' flytrap"] },
  { scientificName: "Dracaena angolensis", commonNames: ["cylindrical snake plant"] },
  { scientificName: "Dracaena fragrans", commonNames: ["corn plant","Dracaena 'Janet Craig Compact'","Fragrant Dracaena","Happy plant"] },
  { scientificName: "Dracaena marginata", commonNames: ["dragon tree"] },
  { scientificName: "Dracaena sanderiana", commonNames: ["lucky bamboo","Belgian evergreen","Chinese water bamboo","Goddess of Mercy's plant"] },
  { scientificName: "Dracaena trifasciata", commonNames: ["snake plant","Snake plant, Mother-in-law's tongue, Viper's bowstring hemp, Snake Sansevieria, Bowstring hemp, Good luck plant, Mother-in-law's nose"] },
  { scientificName: "Drosera capensis", commonNames: ["cape sundew"] },
  { scientificName: "Dryopteris erythrosora", commonNames: ["autumn fern","Japanese shield fern"] },
  { scientificName: "Dypsis lutescens", commonNames: ["areca palm","Yellow Butterfly Palm","butterfly palm","cane palm"] },
  { scientificName: "Echeveria elegans", commonNames: ["echeveria","Mexican snowball","Mexican-gem","pearl echeveria","white Mexican-rose"] },
  { scientificName: "Echinacea purpurea", commonNames: ["echinacea","Eastern Purple Coneflower","Purple Coneflower","Purple-coneflower","broad-leaved purple coneflower"] },
  { scientificName: "Echinocactus grusonii", commonNames: ["golden barrel cactus","barrel cactus","gold barrell cactus","gold-ball cactus","mother-in-law's-seat"] },
  { scientificName: "Epiphyllum anguliger", commonNames: ["fishbone cactus"] },
  { scientificName: "Epipremnum aureum", commonNames: ["golden pothos","Devil's Ivy","Golden pothos, Silver Vine, Money Plant, Devil's Ivy, Solomon Islands' Ivy, Hunter's robe, Ivy arum, Taro vine, Devil's vine","Ivy-arum","Marble Queen"] },
  { scientificName: "Epipremnum pinnatum", commonNames: ["dragon tail plant","Centipede tongavine","Dragon-tail","Native Monstera","Pothos, Tongavine, Centipede tongavine, Dragon-tail plant"] },
  { scientificName: "Eruca vesicaria", commonNames: ["arugula","Gaden Eruca","Garden Rocket","Rocket","Rocket Salad"] },
  { scientificName: "Euphorbia milii", commonNames: ["crown of thorns","Christ's-plant","Christ's-thorn","Christplant","Crown of thorns, Christ plant, Christ thorn"] },
  { scientificName: "Euphorbia pulcherrima", commonNames: ["poinsettia","Christmas-flower","Christmas-star","Mexican flameleaf"] },
  { scientificName: "Euphorbia tirucalli", commonNames: ["pencil cactus","African milkbush","Indian tree spurge","Indiantree Spurge","fingertree"] },
  { scientificName: "Euphorbia trigona", commonNames: ["african milk tree","African milktree"] },
  { scientificName: "Ficus benghalensis", commonNames: ["ficus audrey","Bengal banyan","Bengal fig","Bot","East Indian figtree"] },
  { scientificName: "Ficus benjamina", commonNames: ["weeping fig","Ficus","Java fig","Javatree","Malayan banyan"] },
  { scientificName: "Ficus carica", commonNames: ["common fig","Edible Fig","Fig","Fig Tree"] },
  { scientificName: "Ficus elastica", commonNames: ["rubber plant","India Rubber Tree","Indian Rubber Tree","Rubber Fig"] },
  { scientificName: "Ficus lyrata", commonNames: ["fiddle leaf fig","Fiddle-leaf Fig","Fiddleleaf Fig","banjo fig","lyre-leaf figtree"] },
  { scientificName: "Ficus pumila", commonNames: ["creeping fig","Climbing fig","Climbingfig","creeping rubberplant"] },
  { scientificName: "Fittonia albivenis", commonNames: ["nerve plant","mosaic-plant","nerveplant","silver fittonia","silver netleaf"] },
  { scientificName: "Foeniculum vulgare", commonNames: ["fennel","Aniseed-weed","Sweet Fennel","Venkel"] },
  { scientificName: "Fragaria ananassa", commonNames: ["strawberry","Garden Strawberry","cultivated strawberry","dessert strawberry"] },
  { scientificName: "Fuchsia magellanica", commonNames: ["hardy fuchsia","Fuchsia","Hummingbird Fuchshia"] },
  { scientificName: "Gardenia jasminoides", commonNames: ["gardenia","Cape Jasmine","Cape-jessamine","Gargenia","cape-jasmine"] },
  { scientificName: "Gasteria bicolor", commonNames: ["ox tongue"] },
  { scientificName: "Gerbera jamesonii", commonNames: ["gerbera daisy","African daisy","Barberton Daisy","Barberton Gerbera"] },
  { scientificName: "Graptopetalum paraguayense", commonNames: ["ghost plant","Ghost-plant","ghostplant","mother-of-pearl-plant"] },
  { scientificName: "Guzmania lingulata", commonNames: ["scarlet star","Droophead Tufted Airplant","Scarlet-star"] },
  { scientificName: "Gymnocalycium mihanovichii", commonNames: ["moon cactus","red-cap"] },
  { scientificName: "Gynura aurantiaca", commonNames: ["purple passion plant","Velvetplant","purple velvetplant","purple-passionvine","royal velvetplant"] },
  { scientificName: "Haworthia cooperi", commonNames: ["haworthia","Bristle Haworthia"] },
  { scientificName: "Haworthiopsis attenuata", commonNames: ["zebra haworthia"] },
  { scientificName: "Hedera helix", commonNames: ["english ivy","English Ivy, Common Ivy, European Ivy, Ivy, Needlepoint Ivy, Ripple Ivy","Ivy","Common Ivy"] },
  { scientificName: "Helianthus annuus", commonNames: ["sunflower","Annual Sunflower","Common Sunflower","Mirasol","Ornamental Sunflower"] },
  { scientificName: "Hibiscus rosa-sinensis", commonNames: ["hibiscus","China-rose","Chinese Hibiscus","Hawaiian hibiscus"] },
  { scientificName: "Hippeastrum vittatum", commonNames: ["amaryllis"] },
  { scientificName: "Howea forsteriana", commonNames: ["kentia palm","Forster sentry palm","Sentrypalm","Thatch Palm"] },
  { scientificName: "Hoya carnosa", commonNames: ["wax plant","Common Wax-plant","Porcelainflower","honeyplant","waxflower"] },
  { scientificName: "Hoya kerrii", commonNames: ["sweetheart hoya","Heart Hoya"] },
  { scientificName: "Hydrangea macrophylla", commonNames: ["hydrangea","Bigleaf Hydrangea","Chinese sweetleaf","French hydrangea"] },
  { scientificName: "Hypoestes phyllostachya", commonNames: ["polka dot plant","Baby's Tears","Flamingo Plant","Polkadot-Plant","flamingo-plant"] },
  { scientificName: "Impatiens walleriana", commonNames: ["impatiens","Busy Lizzie","Busy Lizzie, Bizzy lizzy, Balsam, Zanzibar balsam, Sultana, Sultan's flower, Sultan's balsam, Impatiens, Garden impatiens, Patience plant, Patient Lucy","Buzzy lizzy","balsam"] },
  { scientificName: "Ipomoea batatas", commonNames: ["sweet potato","Sweetpotato","Yam","`Uala"] },
  { scientificName: "Jasminum officinale", commonNames: ["jasmine","Poet's jasmine","Summer Jasmine","common jasmine"] },
  { scientificName: "Kalanchoe blossfeldiana", commonNames: ["kalanchoe","Christmas kalanchoe","Flaming Katy","Florist Kalanchoe","Madagascar Widow's-Thrill"] },
  { scientificName: "Kalanchoe daigremontiana", commonNames: ["mother of thousands","Alligator Plant","Devil's Backbone","Mother-of-Millions"] },
  { scientificName: "Kalanchoe luciae", commonNames: ["paddle plant"] },
  { scientificName: "Kalanchoe tomentosa", commonNames: ["panda plant"] },
  { scientificName: "Lactuca sativa", commonNames: ["lettuce","Garden Lettuce","Romaine Lettuce","cultivated lettuce"] },
  { scientificName: "Laurus nobilis", commonNames: ["bay laurel","Bay","Bay Leaf Tree","Grecian laurel"] },
  { scientificName: "Lavandula angustifolia", commonNames: ["lavender","English Lavendar","English Lavender","Garden Lavender"] },
  { scientificName: "Lithops lesliei", commonNames: ["living stones"] },
  { scientificName: "Livistona chinensis", commonNames: ["chinese fan palm","Chinese fan palm, Fountain palm","Chinese fountain palm","Fountain Palm"] },
  { scientificName: "Ludisia discolor", commonNames: ["jewel orchid"] },
  { scientificName: "Mammillaria hahniana", commonNames: ["old lady cactus","old woman cactus","old-lady pincushion"] },
  { scientificName: "Mandevilla sanderi", commonNames: ["mandevilla","Brazilian jasmine","Brazilian-jasmine","Mexican love vine"] },
  { scientificName: "Maranta leuconeura", commonNames: ["prayer plant","prayerplant","ten-commandments"] },
  { scientificName: "Matricaria chamomilla", commonNames: ["chamomile","Annual Chamomile","Blue Chamomile","Common Chamomile"] },
  { scientificName: "Melissa officinalis", commonNames: ["lemon balm","Balm","Beebalm","Common Balm","Lemonbalm"] },
  { scientificName: "Mentha piperita", commonNames: ["peppermint","Black Peppermint","Curly Mint","Hairy Peppermint"] },
  { scientificName: "Mentha spicata", commonNames: ["mint","Bush Mint","Spear Mint","Spearmint"] },
  { scientificName: "Microsorum musifolium", commonNames: ["crocodile fern"] },
  { scientificName: "Monstera adansonii", commonNames: ["swiss cheese plant","Adanson's Monstera","Monkey-Mask","Mountain Ears","Swiss cheese-plant"] },
  { scientificName: "Monstera deliciosa", commonNames: ["monstera","Ceriman","Cut-leaf-philodendron","Delicious Monster","Fruit salad plant"] },
  { scientificName: "Musa acuminata", commonNames: ["banana plant","Cavendish banana","Chinese banana","Edible Banana","Wild Banana"] },
  { scientificName: "Neoregelia carolinae", commonNames: ["blushing bromeliad"] },
  { scientificName: "Nepenthes alata", commonNames: ["tropical pitcher plant"] },
  { scientificName: "Nepeta cataria", commonNames: ["catnip","Cat Mint","Cat-Mint","Catmint"] },
  { scientificName: "Nephrolepis exaltata", commonNames: ["boston fern","Boston Swordfern","Boston sword fern","Sword Fern"] },
  { scientificName: "Nephrolepis obliterata", commonNames: ["kimberly queen fern","Australian sword fern","Kimberley Queen fern"] },
  { scientificName: "Ocimum basilicum", commonNames: ["basil","Sweet Basil","sweet-basil","thai basil"] },
  { scientificName: "Ocimum tenuiflorum", commonNames: ["holy basil","Krishna Tulsi","brush-leaf-tea","sacred basil"] },
  { scientificName: "Olea europaea", commonNames: ["olive tree","Olive","oliveleaf","small-fruit olive"] },
  { scientificName: "Oncidium sphacelatum", commonNames: ["dancing lady orchid","Kandyan Dancer Orchid"] },
  { scientificName: "Opuntia ficus-indica", commonNames: ["prickly pear","Barbary fig","Barbary-fig","Barberry Fig","Cochineal Fig"] },
  { scientificName: "Opuntia microdasys", commonNames: ["bunny ears cactus","Angel's-wings","Cow-Blinder","Dwarf Cactus"] },
  { scientificName: "Origanum majorana", commonNames: ["marjoram","Pot Majoram","Pot Marjoram","Pot Marjorum","Sweet marjoram"] },
  { scientificName: "Origanum vulgare", commonNames: ["oregano","Wild Marjoram","winter sweet"] },
  { scientificName: "Pachira aquatica", commonNames: ["money tree","Guiana-Chestnut","Malabar Chestnut","Malabar chestnut, French peanut, Guiana chestnut, Provision tree, Saba nut","Malabar-chestnut"] },
  { scientificName: "Paphiopedilum insigne", commonNames: ["lady slipper orchid","Splendid Paphiopedilum"] },
  { scientificName: "Passiflora edulis", commonNames: ["passionfruit","Passion Fruit","Passionfruit, Purple granadilla, Purple passionfruit, Black passion fruit","Purple granadilla","common passionfruit"] },
  { scientificName: "Pelargonium zonale", commonNames: ["geranium","Horse-shoe Pelargonium","Horseshoe Geranium","Horseshoe Pelargonium","Horseshoe Storksbill"] },
  { scientificName: "Pellaea rotundifolia", commonNames: ["button fern"] },
  { scientificName: "Peperomia argyreia", commonNames: ["watermelon peperomia","watermelon pepper","watermelon-begonia"] },
  { scientificName: "Peperomia caperata", commonNames: ["emerald ripple peperomia","Emerald-Ripple Peperomia","emerald-ripple pepper","green-ripple pepper","little fantasy pepper"] },
  { scientificName: "Peperomia obtusifolia", commonNames: ["baby rubber plant","American rubberplant","Baby Rubberplant","oval-leaf peperomia","pepper-face"] },
  { scientificName: "Peperomia polybotrya", commonNames: ["raindrop peperomia"] },
  { scientificName: "Peperomia prostrata", commonNames: ["string of turtles"] },
  { scientificName: "Peperomia rotundifolia", commonNames: ["trailing jade peperomia","Yerba Linda"] },
  { scientificName: "Persea americana", commonNames: ["avocado","Avocado, Alligator Pear","Pear Tree","Avocado Pear"] },
  { scientificName: "Petroselinum crispum", commonNames: ["parsley","Garden Parsley","Common Parsley"] },
  { scientificName: "Phalaenopsis amabilis", commonNames: ["orchid"] },
  { scientificName: "Phalaenopsis aphrodite", commonNames: ["moth orchid"] },
  { scientificName: "Phaseolus vulgaris", commonNames: ["common bean","Bean","Common Haricot","Dwarf Bean"] },
  { scientificName: "Philodendron bipinnatifidum", commonNames: ["tree philodendron"] },
  { scientificName: "Philodendron erubescens", commonNames: ["blushing philodendron","Philodendron","red-leaf philodendron"] },
  { scientificName: "Philodendron gloriosum", commonNames: ["velvet leaf philodendron"] },
  { scientificName: "Philodendron hastatum", commonNames: ["silver sword philodendron"] },
  { scientificName: "Philodendron hederaceum", commonNames: ["heartleaf philodendron","Vilevine","heart-leaf philodendron"] },
  { scientificName: "Philodendron melanochrysum", commonNames: ["black gold philodendron","black-gold philodendron"] },
  { scientificName: "Philodendron squamiferum", commonNames: ["philodendron squamiferum"] },
  { scientificName: "Phlebodium aureum", commonNames: ["blue star fern","Gold-foot Fern","Golden Polypody","Golden Polypody, Gold-foot fern","Hare-foot Fern"] },
  { scientificName: "Phoenix roebelenii", commonNames: ["pygmy date palm","Dwarf Date Palm","Roebelin palm","miniature date palm"] },
  { scientificName: "Pilea cadierei", commonNames: ["aluminum plant","Aluminium Plant","Watermelon pilea"] },
  { scientificName: "Pilea microphylla", commonNames: ["artillery plant","Artillery plant, Gunpowder plant","Artillery-plant","Creeping Charly","Lace Plant"] },
  { scientificName: "Pilea peperomioides", commonNames: ["chinese money plant"] },
  { scientificName: "Pinguicula moranensis", commonNames: ["butterwort"] },
  { scientificName: "Pisum sativum", commonNames: ["pea","Common Pea","Field Pea","Garden Pea","Green Pea"] },
  { scientificName: "Platycerium bifurcatum", commonNames: ["staghorn fern","Elkhorn Fern","common staghorn fern"] },
  { scientificName: "Portulacaria afra", commonNames: ["elephant bush","Common Spekboom","Elephant Food","Elephant's Food"] },
  { scientificName: "Raphanus sativus", commonNames: ["radish","Cultivated Radish","Garden Radish","Wild Radish"] },
  { scientificName: "Ravenea rivularis", commonNames: ["majesty palm","Majestic Palm"] },
  { scientificName: "Rhaphidophora tetrasperma", commonNames: ["mini monstera"] },
  { scientificName: "Rhapis excelsa", commonNames: ["lady palm","Broadleaf Lady Palm","Little Lady Palm","bamboo palm"] },
  { scientificName: "Rhipsalis baccifera", commonNames: ["mistletoe cactus"] },
  { scientificName: "Rhododendron simsii", commonNames: ["florist azalea","Formosa Azalea","Red Azalea","Rhododendron"] },
  { scientificName: "Rubus idaeus", commonNames: ["raspberry","American Red Raspberry","Common Red Raspberry","Raspberry, Red Raspberry"] },
  { scientificName: "Salvia officinalis", commonNames: ["sage","Common Sage","Culinary Sage","Golden Sage","Kitchen Sage"] },
  { scientificName: "Salvia rosmarinus", commonNames: ["rosemary"] },
  { scientificName: "Sarracenia purpurea", commonNames: ["purple pitcher plant","Common Pitcherplant","Frog's-britches","Hollow-leaved Lavender","Huntsman's-cup"] },
  { scientificName: "Schefflera actinophylla", commonNames: ["umbrella tree","Australian cabbagetree","Australian umbrella-tree","Octopus tree","Queensland umbrella-tree"] },
  { scientificName: "Schefflera arboricola", commonNames: ["dwarf umbrella tree"] },
  { scientificName: "Schefflera elegantissima", commonNames: ["false aralia"] },
  { scientificName: "Schlumbergera truncata", commonNames: ["christmas cactus","False Christmas Cactus","Thanksgiving cactus","claw cactus","crab cactus"] },
  { scientificName: "Scindapsus pictus", commonNames: ["satin pothos","silver pothos"] },
  { scientificName: "Sedum morganianum", commonNames: ["burro's tail","Donkeytail","burro's-tail","donkey's-tail"] },
  { scientificName: "Sempervivum tectorum", commonNames: ["hens and chicks","Common Houseleek","House-Leek","Houseleek","hen-and-chickens"] },
  { scientificName: "Sinningia speciosa", commonNames: ["gloxinia","Brazilian Gloxinia","Brazilian or Florists Gloxinia","florist's gloxinia"] },
  { scientificName: "Solanum lycopersicum", commonNames: ["tomato","Garden Tomato"] },
  { scientificName: "Solanum melongena", commonNames: ["eggplant","Aubergine","Garden Eggplant, Eggplant","brinjal"] },
  { scientificName: "Solanum tuberosum", commonNames: ["potato","Irish Potato"] },
  { scientificName: "Spathiphyllum wallisii", commonNames: ["peace lily"] },
  { scientificName: "Spinacia oleracea", commonNames: ["spinach","Spinach [plant]","Spinash"] },
  { scientificName: "Stevia rebaudiana", commonNames: ["stevia","Candyleaf","sweet-leaf-of-Paraguay","Azucaca"] },
  { scientificName: "Strelitzia reginae", commonNames: ["bird of paradise","Bird-Of-Paradise","common bird-of-paradise flower","craneflower"] },
  { scientificName: "Streptocarpus ionanthus", commonNames: ["african violet","African-violet","Usambara-violet"] },
  { scientificName: "Strobilanthes dyeriana", commonNames: ["persian shield","Persian-shield"] },
  { scientificName: "Stromanthe sanguinea", commonNames: ["stromanthe"] },
  { scientificName: "Syngonium podophyllum", commonNames: ["arrowhead plant","African evergreen","American Evergreen","Arrow-Head Vine"] },
  { scientificName: "Tagetes erecta", commonNames: ["marigold","African Marigold","African Or French Marigold","American Marigold","Aztec Marigold"] },
  { scientificName: "Thymus vulgaris", commonNames: ["thyme","Common Thyme","English Thyme","Garden Thyme"] },
  { scientificName: "Tillandsia ionantha", commonNames: ["air plant","Blushing Bride","Blushing Bride Airplant","Enhanced Lilac","Ionantha Lilac"] },
  { scientificName: "Trachelospermum jasminoides", commonNames: ["star jasmine","Chinese star-jessamine","Confederate Jasmine","Confederate-jessamine","Hairy star jasmine"] },
  { scientificName: "Tradescantia fluminensis", commonNames: ["small-leaf spiderwort","Wandering Jew","Wandering-Jew","small-leaved spiderwort"] },
  { scientificName: "Tradescantia pallida", commonNames: ["purple heart","\"Wandering Jew\"","Purple Queen","purpleheart"] },
  { scientificName: "Tradescantia spathacea", commonNames: ["moses in the cradle","Boatlily","Boatlily, Moses-in-the-cradle, Oysterplant, Moses-in-a-boat, Cradle Lily, Moses on a Raft, Moses in the Bulrushes, Men in a Boat","Moses-in-the-basket","Moses-in-the-cradle"] },
  { scientificName: "Tradescantia zebrina", commonNames: ["wandering jew","Inch-plant","Inchplant","Inchplant, Wandering jew, Cockroach grass, Purple wandering Jew, Silver inch plant, Striped trad, Striped wandering creeper, Striped wandering Jew, Wandering zebrina, Zebra plant","wandering-Jew"] },
  { scientificName: "Tropaeolum majus", commonNames: ["nasturtium","Garden Nasturtium","Indian Cress","Lark's Heel","Monk Cress"] },
  { scientificName: "Vaccinium corymbosum", commonNames: ["blueberry","American Blueberry","Highbush Blueberry","New Jersey Blueberry"] },
  { scientificName: "Vanda coerulea", commonNames: ["vanda orchid","Blue Orchid","Blue vanda"] },
  { scientificName: "Vanilla planifolia", commonNames: ["vanilla orchid","Bourbon vanilla","Flat-leaved Vanilla","Vanilla","vanilla bean"] },
  { scientificName: "Vitis vinifera", commonNames: ["grape","Common Grapevine","European Grape","European wine grape"] },
  { scientificName: "Vriesea splendens", commonNames: ["flaming sword","flaming-sword"] },
  { scientificName: "Yucca gigantea", commonNames: ["spineless yucca"] },
  { scientificName: "Zamioculcas zamiifolia", commonNames: ["ZZ plant","Zanzibar gem","zeezee plant"] },
  { scientificName: "Zantedeschia aethiopica", commonNames: ["calla lily","Altar-Lily","Arum Lily","Arun Lily"] },
  { scientificName: "Zea mays", commonNames: ["corn","Indian Corn","Maize","Mandamin"] },
  { scientificName: "Zingiber officinale", commonNames: ["ginger","Cooking Ginger","Garden Ginger","common ginger"] },
];
